import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { GNB } from './component/GNB'
import { Footer } from './component/Footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Interrupt',
  description: 'Generated by KwonSeungMin',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GNB />
        <div className='web'>{children}</div>
        <Footer />
        </body>
    </html>
  )
}
